version: '3.12'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=system_memory
      - POSTGRES_HOST=db
    ports:
      - 5432:5432
  backend:
    build: .
    command:   python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=system_memory
      - POSTGRES_HOST=db
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - D:/backend/DjangoJiraClone:/usr/src/app
    ports:
      - 8000:8000


volumes:
  postgres-data: