# Generated by Django 5.0.2 on 2024-04-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=800)),
                ('work_date', models.DateField(null=True)),
                ('work_time', models.IntegerField(null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.user')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkOnTask',
        ),
    ]
